### ISSUE TITLE
Timeline display missing line breaks or helpful formatting

### ISSUE THREAD

**Issue by jeanconn** [x-calibre/astropython#42]
It looks like the timeline fields kind of run together as in "JWSTHomepage" .

![screen shot 2015-07-09 at 10 30 24 am](https://cloud.githubusercontent.com/assets/791508/8600863/efafba3e-262d-11e5-81d2-11bf30e69c08.png)

**Comment by x-calibre** [comment]
Thanks a lot for bringing this up !

This is not a problem relating to out web application , but the old AstroPython website, where all the content was put together ... so what you are seeing there are not separate fields , but the old author typing in the content in a single body(and not separate "Description" and "HomepageURL"  fields)

The timeline  body displays only the abstract of the article (if provided) or the first 300 words of the body (as in this case) and no other field !

There is only 1 solution to this problem . Manually store all the old AstroPython entries into our new web app !

**Comment by jeanconn** [comment]
I'm a little confused about this, because the line breaks look right at,
say:

http://amanjhunjhunwala.pythonanywhere.com/packages/webbpsf71/

**Comment by x-calibre** [comment]
yes , it does , but when a post is rendered on the TIMELINE , all the html in the body is stripped out ! 
If that is not done, there would be many non-closed tags like 
![image](https://cloud.githubusercontent.com/assets/10886527/8604704/d9bb7de2-269d-11e5-8ad7-c8e63a9c8ef4.png)

However ,because the length of the abstract is constrained , any html present in the abstract is rendered !

**Comment by jeanconn** [comment]
Gotcha.  Thanks!​
