### ISSUE TITLE
Confirm that ported_data is a full copy of legacy astropython.org contents

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#47]

**Comment by jeanconn** [comment]
Did you open this issue for general handling of this, or specifically related to https://github.com/x-calibre/astropython/commit/43c83a64db7087ea6769caa55451af20fc42752a ?

**Comment by x-calibre** [comment]
It is a full copy of all the contents present on the astropython.org site .The problem with the ported data in 1 of the tutorials and code snippet is the confusion between `"` and `'` that the MySQL DB on PA is facing when parsing those 2 JSON files .... I will manually correct them and add them later (It however works on SQLite3 and PostGRE DBs )

**Comment by taldcroft** [comment]
This is an informational question on my part.  I just want to be sure that what is in the git repo now is (or will be soon) "the final copy".  

This is related in part to the fact that google app engine is forcing me to work on the legacy site to migrate to a new back end.  The timing is such that I can probably keep the legacy site limping along for another month or so (with very little work), and then it will be gone forever.  Initial efforts at migrating the site stalled out, so I want to know that if I reach the point of diminishing returns then we'll be good with no more access to the live GAE site.

**Comment by x-calibre** [comment]
@taldcroft  does all the new content on the PythonAnywhere server match up the old astropython DB?
If it does , then we can let go of the old database.
The one thing that is probably missing are the email -ids of the users we had in the earlier site. I couldn't extract them, and I think they were not present in the GAE dump. 

However, for security sake, we could store the dump and the old SDKs so that we may run it our local servers in case anything is left out.

**Comment by taldcroft** [comment]
OK, this sounds good.  I'm not too concerned about the email IDs.  Good point about keeping the old SDK going.  I have a local copy along with Python 2.5 to run it.  I think it won't be long before it is irrelevant.
