### ISSUE TITLE
[DISCUSS] Visual design and aesthetics

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#80]

**Comment by bsipocz** [comment]
:+1: for the design. 
(The smiling planets are a bit strange at first, but one get to like them on the second look :smile:  ). However would it be easy to point the space telescope off the earth? :wink:

**Comment by bsipocz** [comment]
Have you think of having a cloud like alphabetical tagging (more often used tags are bigger, than rare ones, etc) rather than the current non-alphabetical one at the side? I foresee it would be helpful.

**Comment by KathleenLabrie** [comment]
The homepage takes way too long load.  Do we really need smiley planets?...  The initial feel is a bit too childish for my taste. 

I also find the various animations throughout distracting.  Maybe I'm just too old school, but I like my reference websites to be to the point, no fluff, and compact.  This is a bit too "airy" for me.  Screen real-estate is too valuable.  I have a case now on my screen with a large chunk of white space in the middle.  If I try to resize the browser, it doesn't just get rid of the white, unused area, it just cuts information that now becomes offscreen.  (eg. http://amanjhunjhunwala.pythonanywhere.com/packages/poppy97/)

The yellow in the "Python" of the AstroPython logo does not match the more subdue yellow used throughout the website.  Also, because the logo is on a white background, the bright yellow "Python" is a bit hard to see.   I very much like the white and subdued-yellow color theme by the way.

Anyway, those are the first impression I had.

**Comment by evertrol** [comment]
The contrast is low, in particular between the main font and background. The web developer inspector tools actually teel me the CSS is black on (nearly) white, but comparing to e.g. the black in the turtle editor, the text definitely isn't near black. Turning off javascript didn't help, but it seems something odd is going on (shouldn't be my browser, since I've tried this on Linux + Firefox, OS X + Firefox, OS X + Safari). Perhaps it's the font itself that it very thin.
The yellow tags on e.g. the packages page have the same issue: too low contrast.

I agree with KathleenLabrie's comment on the animations: they make things distracting (like the fade-in of the blurbs of "Latests Posts", and make the frontpage take too long to get to its final state. And the fly-in submenu's become quite irritating imo.

I think there are also, overall, too many elements at once on a page. E.g., going to a blog post, I see
* a small top menu  (login/f/g/github)
* a menu
* title
* blog post / announcement
* list of recent posts next to it
* tags below it
* like/dislike (+ counter) icons
* share/f/t/g/email buttons
* comment section
* tag lines from Disqus
* 3 columns with feed subscription/contribute blurb/feedback-contribute-contact
* again social media buttons

The actual blog post is dwarfed by its surroundings, and essentially gets lost. It's a bit better when the post is longer, but it still feels there's too much on a single page.

**Comment by x-calibre** [comment]
Thank you  everyone for taking the time out for the feedback !
@bsipocz : Glad you liked the application! Cloud tagging is in the pipeline currently and is going to added soon ! The only thing going against its favor is the huge hit in time it would take to load the posts (Firing up queries for each and every tag)

@KathleenLabrie @evertrol : @taldcroft  had suggested exactly the same - "screen real estate is of great value". The animations throughout the website are just tricks to engage new users and hopefully get them to contribute ! We will certainly integrate the feedback and have a faster, more compact information-rich front page that everyone is happy with ! 
There is definitely going to be work on the logo and font as well along with the general-organization of the pages, so the page does not look crowded ! 

Thank you again for your feedback !

**Comment by bsipocz** [comment]
@x-calibre - I'm totally inexperienced in web development, and just wonder whether some caching or DB backend can be used for that which queries the tags only once a day or similar.

**Comment by Gabriel-p** [comment]
The site is not particularly heavy (see: http://tools.pingdom.com/fpt/#!/bfYbyU/http://amanjhunjhunwala.pythonanywhere.com/), I'd mainly improve the contrast.

The down pointing arros to the left of "Teach and learn" and "Forum" should be a few extra pixels apart.

Also, the Trinket module is dead for me, not sure if it's not yet functional.

**Comment by x-calibre** [comment]
@bsipocz@KathleenLabrie@evertol@Gabriel-p we have changed the logo, improvised a lot on the colors and fonts, decreased crowding around post-display....Please have a look... we would like to to know if the issues have been resolved! Thank you !

Site:
http://amanjhunjhunwala.pythonanywhere.com/ for front page

Single Post :
http://amanjhunjhunwala.pythonanywhere.com/tutorials/installing-python-via-macports-on-mac32/

**Comment by KathleenLabrie** [comment]
@x-calibre It is more compact, that's good.  The homepage still takes 3 to 5 seconds to load (with the spinning gear thing.)  Without the smiley planet on the right, that space is not a big white, unused space.  Any plans to put something there?

I'm still not a big fan of the animation but that's probably just a matter taste.

**Comment by x-calibre** [comment]
We are definitely coming up with better main page plans ! (More information on the main page is definitely a priority !) Any ideas would be great !
Sorry, for the late reply , I dont know how I lost this in the notifications !

**Comment by Gabriel-p** [comment]
The bottom bar (date / love) that shows for each Teach & Learn / Forum / Packages entry should be aligned for all entries. See image below.

![captura de pantalla de 2015-07-30 14 13 30](https://cloud.githubusercontent.com/assets/6054951/8989907/6fb38588-36c5-11e5-8d91-6c04c3570d74.png)

**Comment by x-calibre** [comment]
@Gabriel-p Thank you so much for pointing it out ! I initially thought that such an irregular look would give it a more natural feel, but once I made them all of the same height (as you said) the look was MUCH better and so much more uniform ! Thanks for the suggestion again,the issue has been rectified ...
![image](https://cloud.githubusercontent.com/assets/10886527/8992183/d47a7d5a-371a-11e5-8fe3-7a5e580bf5bf.png)

**Comment by Gabriel-p** [comment]
:+1: 

Just watch out for this:

![captura de pantalla de 2015-07-30 16 02 23](https://cloud.githubusercontent.com/assets/6054951/8992398/92684f78-36d4-11e5-8696-d151b4afbc7e.png)

the text is not being trimmed with (...) as it should.

Also, perhaps the vertical space allowed for the title of entries should be fixed. Otherwise you end up with entries with a large title pushing content down and making it look not so good for entries with a shorter title, ie:

![captura de pantalla de 2015-07-30 16 06 32](https://cloud.githubusercontent.com/assets/6054951/8992508/3635e7a0-36d5-11e5-893f-ac0093d2a5af.png)

**Comment by cdeil** [comment]
Overall – great job, thanks a lot!

I think the header takes up too much space ... on every single page I have to scroll down before I see the content ...
<img width="1423" alt="screen shot 2015-08-02 at 17 41 23" src="https://cloud.githubusercontent.com/assets/852409/9026815/d8ce1900-393d-11e5-9d02-45298e0c1e3b.png">

**Comment by cdeil** [comment]
Not sure this element (horizontal line with geometric shapes below, cut off by the line) is great to separate parts of the page ... I'm on a slow internet connection and at first thought this was a partially loaded Figure or mis-rendered part of the page. Maybe something simpler?

<img width="1232" alt="screen shot 2015-08-02 at 17 44 14" src="https://cloud.githubusercontent.com/assets/852409/9026822/22daccaa-393e-11e5-8478-460ce0c8d625.png">

**Comment by x-calibre** [comment]
@cdeil  Thank you so much for taking the time out for the feedback over this and all the other topics. These will be rectified soon !
