### ISSUE TITLE
Rating is possible without being signed in

### ISSUE THREAD

**Issue by cdeil** [x-calibre/astropython#99]
I went to  http://amanjhunjhunwala.pythonanywhere.com/packages/alipy74/ with Chrome and could rate that package without being signed it.
Then I went to the same page with Safari and was able to rate it again, i.e. it now has two thumbs up from me.

I guess rating should only be possible once and for users that are signed in?
Otherwise people can easily screw with all the numbers by writing some script?

**Comment by x-calibre** [comment]
Hi, @cdeil ,  I cannot thank you enough for pointing out a big security flaw on the application ! Having "Anonymous Voting" was a feature, we had initially planned with the site... The current technique we use is to generate a unique "token" by hashing the IP Address and "UserAgent"(browser-specific) of a user,so that multiple votes are caught (Clicking on a voted link again, removes the vote) . However I guess we need to use a stronger token generation mechanism (or probably forego Anonymous Voting completely ) so that Agents from multiple browsers are treated the same and the site is safe ! I actually wrote a Python Script and tried to break the system, but all it did was toggle from +1 to 0 and back .... but I agree that there could be more sophisticated ways to break in ! It will be rectified soon !

**Comment by cdeil** [comment]
I think only allowing logged in users to vote is OK.
With the "log in with X" feature it only takes a few seconds.
And that's what other sites, e.g. Stackoverflow, do, right?

One more thing I noticed ... I can log in with Github and Google and this is seen as two different users, i.e. I can vote twice and if I accidentally log in with one once and the other at some other time, my posts will be distributed on two users on your site. I don't know if that's just how it is, or if there's a way to fix this.

**Comment by x-calibre** [comment]
Email ID is the unique field here ! If you have used the same Email ID over Github and Google, you will have only 1 account. The moment you shift email ids , a new account is created !
All the info we get from Github, Google and Facebook is an email id , so we had no other choice !

**Comment by cdeil** [comment]
I understand. It's not unlikely this will happen, though. And people change email over the years.
This could mean quite a few users have their contributions split across multiple accounts on your site, which is not nice.

How do other sites that use OAuth handle this issue?

**Comment by x-calibre** [comment]
I have implemented a new algorithm for the ratings which should now hold, also multiple social accounts can now be connected to one user (the option is under "Profile") . Should I close this ,then ?
